name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m unittest test_discriminant.py
        
    - name: Run flake8
      run: |
        flake8 *.py --max-line-length=79
        
    - name: Check coverage
      run: |
        coverage run -m unittest test_discriminant.py
        coverage report
        
    - name: Run bandit
      run: |
        bandit *.py
        
    - name: Send Telegram notification
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          Repository: ${{ github.repository }}
          Status: ${{ job.status }}
          Branch: ${{ github.ref }}
          