name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run tests
      run: python -m unittest test_discriminant.py
      
    - name: Check code style
      run: flake8 *.py --max-line-length=100
      
    - name: Check test coverage
      run: |
        coverage run -m unittest test_discriminant.py
        coverage report
        
    - name: Security check
      run: bandit *.py
      
    - name: Send Telegram notification
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          CI Pipeline - ${{ github.repository }}
          Status: ${{ job.status }}
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref }}